global:
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'instances'
    honor_labels: true
    metrics_path: /probe
    params:
      module: [tcp_connect]
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service_port]
        regex: '(8300|8302|8500|8600)'
        action: drop
      - source_labels: [__address__]
        regex: '([a-zA-Z]).*$'
        action: drop
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox:80 
  - job_name: 'endpoint_health_checks'
    honor_labels: true
    metrics_path: /probe
    params:
      module: [http_2xx]
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: 'monitor_this'
        action: keep
        target_label: __param_target
      - target_label: __param_target
        replacement: prometheus-blackbox:80 
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "prometheus-alertmanager"
rule_files:
- /etc/prometheus/alerting_rules_*.yml
