global:
scrape_configs:
  - job_name: 'docker_hosts'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        action: keep
      - source_labels: [__meta_consul_tags]
        regex: .*,url_health_check,.*
        action: drop
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox:9115 
  - job_name: 'url_health_checks'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,url_health_check,.*
        action: keep
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
			  replacement: ${1}-${2}
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox:9115
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "prometheus-alertmanager:9093"
rule_files:
- /etc/prometheus/alerting_rules_*.yml
