global:
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'services'
    honor_labels: true
    metrics_path: /probe
    params:
      module: [tcp_connect]
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service_id]
        target_label: service
      - source_labels: [__meta_consul_address]
        target_label: instance
      - source_labels: [__meta_consul_tags]
        replacement: prometheus-blackbox:80 
  - job_name: 'endpoint_health_checks'
    honor_labels: true
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    consul_sd_configs:
      - server: 'consul:8500'
        tag: "endpoint_health_check"
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        action: keep
      - source_labels: [__meta_consul_service_address]
        target_label: instance
      - source_labels: [__meta_consul_service_address]
        target_label: __param_target
      - target_label: __address__
        replacement: prometheus-blackbox:80
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "prometheus-alertmanager"
rule_files:
- /etc/prometheus/alerting_rules_*.yml
